Repository hrwakeford/ExoTiC-ISM, pull requests merged in 2021-02, with the labels that each got.

#116 Feature/small fixes and updates
  exoticism/marginalisation.py
  notebooks/tutorials/1_Intro-tutorial.ipynb
  report_template.html
Labels: High Priority, enhancement

#118 Update contributing guidelines and readme
  CONTRIBUTING.md
  README.md
Labels: documentation

#121 Issue120 - add wavelength in output
  exoticism/marginalisation.py
  report_template.html
Labels: enhancement
